### PR TITLE
Add github-wiki-see.page

### PR DESCRIPTION
**Pull request by austintraver**
Discovered as the first result returned by Google when searching for `ideavim sethandler`

<https://github-wiki-see.page/m/JetBrains/ideavim/wiki/sethandler>

### CODE REVIEW

**Comment by nelsonjchen** [comment]
I run https://github-wiki-see.page. Please look at the front page as an explanation of why it exists. GitHub doesn't allow search engines to index many GitHub Wikis and that would be one of them.

**Comment by nelsonjchen** [comment]
If you have any questions or suggestions, please let me know!

**Comment by nelsonjchen** [comment]
As a suggestion, you may want to use some solution involving this to not have the service's interstitial blocking you:

https://github.com/nelsonjchen/github-wiki-see-rs/blob/master/AUTO_REDIRECT_API.md

I am fully committed to keeping that as a stable API. The alternative, as you've proposed here, would block a massive majority of GitHub Wikis from your search results.

**Comment by nelsonjchen** [comment]
@arosh would you take a PR for an comment explanation of https://github-wiki-see.page like what was done in another ublacklist project here?:

https://github.com/quenhus/uBlock-Origin-dev-filter/blob/f736728c3b6a6b1a8630512c050e2b404262934f/data/github_copycats.txt#L56-L63

**Comment by arosh** [comment]
@nelsonjchen @austintraver 
As a matter of fact, I take advantage of GHWSEE. I spent some time looking for a valid reason to exclude GHWSEE from the policies of this project. Sorry for the late response.

Hmm..., as far as I know, there is no other GitHub Wiki copycat at the moment, so can I put it on hold for now? If many such copycats are developed and start polluting Google search results, I'll reconsider.

**Comment by nelsonjchen** [comment]
@arosh That sounds good. For what it is worth, to repeat, I do my best to try to make the service not copy anything that GitHub permits indexing of. Unfortunately, Google is big and they take a long time to update their index sometimes to follow the updates I do on my service to not show up on search results for indexable content. 

@austintraver My apologies for the lag and it showing up on your results, I am doing this as fast as I can and am currently architecting/testing a more permanent, automatic, and responsive solution for this.

**Comment by austintraver** [comment]
Thank you both for contributing thoughtful constructive discussion to the PR. After reading the above, I think my PR is a bit heavy-handed. Marking it as closed.

**Pull request closed without merging**
